/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminWorkArea;

import Business.DMEcosystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.EnterpriseDirectory;
import Business.RegionNetwork.Network;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ankita
 */
public class EnterpriseDetailsTableJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewEnterpriseDetailsJPanel
     */
    
   
    JPanel mainJpanel;
    Enterprise en;
    DMEcosystem es;
    EnterpriseDirectory ed;
    Network nw;
    //String enterpriseType;
    public EnterpriseDetailsTableJPanel(JPanel mainJpanel,DMEcosystem es, EnterpriseDirectory ed) {
        initComponents();
        this.mainJpanel=mainJpanel;
        this.es=es;
        this.ed = ed;
        PopulateTable();
        
      /*  txtName.setText(String.valueOf(en.getEnterpriseName()));
        txtTotalEmployee.setText(String.valueOf(en.getNoofEmployee()));
        txtaddress.setText(String.valueOf(en.getAddress()));
       // ddlenterprisetype.setSelectedItem(Enterprise.EnterpriseType.Client.getValue());
        ddlenterprisetype.setSelectedItem(jLabel1);*/
               
                
    }
      public void PopulateTable()
       {
           DefaultTableModel DTM=(DefaultTableModel)tblEnterprise.getModel();
           DTM.setRowCount(0);
        for (Network N:es.getNetworkList())
        {
           for(Enterprise en: N.getEpd().getEnterpriseList())
           {
                Object[] row  =new Object[3];
                row[0]=en;
                row[1]=N.getName();
                row[2]=en.getNoofEmployee();
                DTM.addRow(row);
           
           }
        }
           
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnview1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEnterprise = new javax.swing.JTable();
        btnconfigureadmin = new javax.swing.JButton();
        txtemailconfig = new javax.swing.JButton();
        txttwitterconfig = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 800));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("            View Enterprise");

        btnview1.setBackground(new java.awt.Color(0, 153, 255));
        btnview1.setForeground(new java.awt.Color(255, 255, 255));
        btnview1.setText("View");
        btnview1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnview1ActionPerformed(evt);
            }
        });

        tblEnterprise.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise Name", "Network", "Number of Employees"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblEnterprise);

        btnconfigureadmin.setBackground(new java.awt.Color(0, 153, 255));
        btnconfigureadmin.setForeground(new java.awt.Color(255, 255, 255));
        btnconfigureadmin.setText("Configure Admin");
        btnconfigureadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfigureadminActionPerformed(evt);
            }
        });

        txtemailconfig.setBackground(new java.awt.Color(0, 153, 255));
        txtemailconfig.setForeground(new java.awt.Color(255, 255, 255));
        txtemailconfig.setText("Configure Email");
        txtemailconfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailconfigActionPerformed(evt);
            }
        });

        txttwitterconfig.setBackground(new java.awt.Color(0, 153, 255));
        txttwitterconfig.setForeground(new java.awt.Color(255, 255, 255));
        txttwitterconfig.setText("Configure Twitter");
        txttwitterconfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttwitterconfigActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnview1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(btnconfigureadmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtemailconfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txttwitterconfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnview1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnconfigureadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtemailconfig, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txttwitterconfig, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(185, 185, 185))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnview1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnview1ActionPerformed
        // TODO add your handling code here:
        int selectedRow=tblEnterprise.getSelectedRow();
        if (selectedRow>=0)
        {
        
            Enterprise en=(Enterprise)tblEnterprise.getValueAt(selectedRow,0);
            ViewEnterpriseDetailsJPanel vp =new ViewEnterpriseDetailsJPanel(mainJpanel,es,en);
            mainJpanel.add("View EnterPrise",vp);
            CardLayout cl=(CardLayout)mainJpanel.getLayout();
            cl.next(mainJpanel);
           // resetTextfield();
            
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Pleases select Row ");
        }
    }//GEN-LAST:event_btnview1ActionPerformed

    private void btnconfigureadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfigureadminActionPerformed
        // TODO add your handling code here:
        
          int selectedRow=tblEnterprise.getSelectedRow();
        if (selectedRow>=0)
        {
        
            Enterprise en=(Enterprise)tblEnterprise.getValueAt(selectedRow,0);
            ManageEnterpriseAdminJPanel vp =new ManageEnterpriseAdminJPanel(mainJpanel,es,en);
            mainJpanel.add("ManageEnterpriseAdminJPanel",vp);
            CardLayout cl=(CardLayout)mainJpanel.getLayout();
            cl.next(mainJpanel);
           // resetTextfield();
            
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Pleases select Row ");
        }
        
    }//GEN-LAST:event_btnconfigureadminActionPerformed

    private void txtemailconfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailconfigActionPerformed
        // TODO add your handling code here:
        
        int selectedRow=tblEnterprise.getSelectedRow();
        if (selectedRow>=0)
        {
        
            Enterprise en=(Enterprise)tblEnterprise.getValueAt(selectedRow,0);
       //     EnterpriseEmailConnectionConfiguration vp =new EnterpriseEmailConnectionConfiguration(mainJpanel,es,en);
//            mainJpanel.add("EnterpriseEmailConnectionConfiguration",vp);
//            CardLayout cl=(CardLayout)mainJpanel.getLayout();
//            cl.next(mainJpanel);
           // resetTextfield();
            
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Pleases select Row ");
        }
        
        
    }//GEN-LAST:event_txtemailconfigActionPerformed

    private void txttwitterconfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttwitterconfigActionPerformed
        // TODO add your handling code here:
        int selectedRow=tblEnterprise.getSelectedRow();
        if (selectedRow>=0)
        {
        
            Enterprise en=(Enterprise)tblEnterprise.getValueAt(selectedRow,0);
            ManageDigitalPlatformConfigurationPanel vp =new ManageDigitalPlatformConfigurationPanel(mainJpanel,es,en);
            mainJpanel.add("ManageDigitalPlatformConfigurationPanel",vp);
            CardLayout cl=(CardLayout)mainJpanel.getLayout();
            cl.next(mainJpanel);
           // resetTextfield();
            
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Pleases select Row ");
        }
        
    }//GEN-LAST:event_txttwitterconfigActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconfigureadmin;
    private javax.swing.JButton btnview1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblEnterprise;
    private javax.swing.JButton txtemailconfig;
    private javax.swing.JButton txttwitterconfig;
    // End of variables declaration//GEN-END:variables
}
