/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminWorkArea;

import Business.DMEcosystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.EnterpriseDirectory;
import Business.RegionNetwork.Network;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ankita
 */
public class EnterpriseDetailsTableJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewEnterpriseDetailsJPanel
     */
    
   
    JPanel mainJpanel;
    Enterprise en;
    DMEcosystem es;
    EnterpriseDirectory ed;
    Network nw;
    //String enterpriseType;
    public EnterpriseDetailsTableJPanel(JPanel mainJpanel,DMEcosystem es, EnterpriseDirectory ed) {
        initComponents();
        this.mainJpanel=mainJpanel;
        this.es=es;
        this.ed = ed;
        PopulateTable();
        
      /*  txtName.setText(String.valueOf(en.getEnterpriseName()));
        txtTotalEmployee.setText(String.valueOf(en.getNoofEmployee()));
        txtaddress.setText(String.valueOf(en.getAddress()));
       // ddlenterprisetype.setSelectedItem(Enterprise.EnterpriseType.Client.getValue());
        ddlenterprisetype.setSelectedItem(jLabel1);*/
               
                
    }
      public void PopulateTable()
       {
           DefaultTableModel DTM=(DefaultTableModel)tblEnterprise.getModel();
           DTM.setRowCount(0);
           for(Enterprise en: ed.getEnterpriseList())
           {
                Object[] row  =new Object[3];
                row[0]=en;
                row[1]=en.getEnterpriseName();
                row[2]=en.getNoofEmployee();
                DTM.addRow(row);
           
           }
           
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnview1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEnterprise = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("            View Enterprise");

        btnview1.setBackground(new java.awt.Color(0, 153, 255));
        btnview1.setForeground(new java.awt.Color(255, 255, 255));
        btnview1.setText("View");
        btnview1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnview1ActionPerformed(evt);
            }
        });

        tblEnterprise.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Enterprise Name", "Number of Employees"
            }
        ));
        jScrollPane2.setViewportView(tblEnterprise);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(btnview1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(btnview1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnview1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnview1ActionPerformed
        // TODO add your handling code here:
         int selectedRow=tblEnterprise.getSelectedRow();
        if (selectedRow>=0)
        {
        
            Enterprise en=(Enterprise)tblEnterprise.getValueAt(selectedRow,0);
            ViewEnterpriseDetailsJPanel vp =new ViewEnterpriseDetailsJPanel(mainJpanel,es,en);
            mainJpanel.add("View EnterPrise",vp);
            CardLayout cl=(CardLayout)mainJpanel.getLayout();
            cl.next(mainJpanel);
           // resetTextfield();
            
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Pleases select Row ");
        }
    }//GEN-LAST:event_btnview1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnview1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblEnterprise;
    // End of variables declaration//GEN-END:variables
}
