package UserInterface.SystemAdminWorkArea;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author iamni
 */
public class EnterpriseEmailConnectionConfiguration extends javax.swing.JPanel {

    /**
     * Creates new form EnterpriseEmailConnectionConfiguration
     */
    public EnterpriseEmailConnectionConfiguration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        txtSMTPhost = new javax.swing.JPasswordField();
        txtSMTPportNo = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        txtRecEmailAdd = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmailConfig = new javax.swing.JTable();
        btnTestConnection = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Configure Email Connection");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 350, 70));

        jLabel2.setText("Password:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 120, -1));
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 240, 30));

        jLabel3.setText("SMTP Host :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 120, -1));

        jLabel4.setText("SMTP Port No :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 120, -1));

        btnSave.setBackground(new java.awt.Color(0, 153, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 150, -1));
        add(txtSMTPhost, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 240, 30));
        add(txtSMTPportNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 240, 30));

        jLabel5.setText("Recepient Email Address:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 120, 30));
        add(txtRecEmailAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 240, 30));

        tblEmailConfig.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise", "Email"
            }
        ));
        jScrollPane1.setViewportView(tblEmailConfig);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 350, 260));

        btnTestConnection.setBackground(new java.awt.Color(0, 153, 255));
        btnTestConnection.setText("Test Connection");
        btnTestConnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestConnectionActionPerformed(evt);
            }
        });
        add(btnTestConnection, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 150, -1));

        btnEdit.setBackground(new java.awt.Color(0, 153, 255));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 170, 150, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        //Enterprise enterprise = (Enterprise) enterpriseJComboBox.getSelectedItem();

       
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnTestConnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestConnectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTestConnectionActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnTestConnection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEmailConfig;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtRecEmailAdd;
    private javax.swing.JPasswordField txtSMTPhost;
    private javax.swing.JPasswordField txtSMTPportNo;
    // End of variables declaration//GEN-END:variables
}
