/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminWorkArea;

import Business.DMEcosystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.RegionNetwork.Network;
import Business.Role.AdminRole;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dhava
 */
public class ManageEnterpriseAdminJPanel extends javax.swing.JPanel {

         private JPanel userProcessContainer;
        private DMEcosystem system;
        private    Enterprise E;
    /**
     * Creates new form ManageEnterpriseAdminJPanel
     */
    public ManageEnterpriseAdminJPanel(JPanel userProcessContainer,DMEcosystem system, Enterprise E) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.system=system;
        this.E=E;
         populateTable() ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtpassword = new javax.swing.JPasswordField();
        txtrepassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbluserlist = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Configure Admin");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 268, 70));

        jLabel2.setText("User Name :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 120, -1));
        add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 240, 30));

        jLabel3.setText("Re-Password :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 120, -1));

        jLabel4.setText("Password :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 120, -1));

        btnSave.setBackground(new java.awt.Color(0, 153, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 150, -1));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Double Left_100px.png"))); // NOI18N
        btnBack.setToolTipText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnBack.setBorderPainted(false);
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 105, 76));
        add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 240, 30));
        add(txtrepassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 240, 30));

        jLabel5.setText("Name :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 120, 30));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 240, 30));

        tbluserlist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Network", "Enterprise", "Name"
            }
        ));
        jScrollPane1.setViewportView(tbluserlist);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, 260));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        // TODO add your handling code here:

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Double Left_100px2.png")));
        btnBack.setBorderPainted(false);
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        // TODO add your handling code here:
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Double Left_100px.png")));
    }//GEN-LAST:event_btnBackMouseExited

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

//        CardLayout layout=(CardLayout) mainJpanel.getLayout();
//        layout.previous(mainJpanel);
//        Component[] comps = mainJpanel.getComponents();
//        for(Component c: comps){
//            if(c instanceof EnterpriseDetailsTableJPanel){
//                EnterpriseDetailsTableJPanel panel = (EnterpriseDetailsTableJPanel) c;
//                panel.PopulateTable();
//            }
//        }
        //        mainJpanel.remove(this);
        //        CardLayout layout = (CardLayout) mainJpanel.getLayout();
        //        layout.previous(mainJpanel);
    }//GEN-LAST:event_btnBackActionPerformed

    
    
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tbluserlist.getModel();

        model.setRowCount(0);
      //  for (Network network : system.getNetworkList()) {
           // for (Enterprise enterprise : network.getEpd().getEnterpriseList()) {
                for (UserAccount userAccount : E.getUserAccountDirectory().getUserAccountList()) {
                    Object[] row = new Object[3];
                    row[0] = E.getNetwork();
                    row[1] = E.getName();
                    row[2] = userAccount.getUsername();

                    model.addRow(row);
                }
           // }
        //}
    }
    
    
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        //Enterprise enterprise = (Enterprise) enterpriseJComboBox.getSelectedItem();
        
        String username = txtUserName.getText();
        String password = String.valueOf(txtpassword.getPassword());
        String repassword = String.valueOf(txtrepassword.getPassword());
        String name = txtName.getText();
        
        if (!password.equals(repassword))
        {
               JOptionPane.showMessageDialog(null, "Password does not match");
        }
        else
        {
            Employee employee = E.getEmployeeDirectory().createEmployee(name);   
            UserAccount account = E.getUserAccountDirectory().createUserAccount(username, password, employee, new AdminRole());
            populateTable() ;
            JOptionPane.showMessageDialog(null, "Enterprise Admin created successfully..!!");
        }
        
        
        
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbluserlist;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JPasswordField txtrepassword;
    // End of variables declaration//GEN-END:variables
}
