/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminWorkArea;

import Business.DMEcosystem;
import Business.RegionNetwork.Network;
import java.awt.CardLayout;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dafhava
 */
public class SystemAdminManageNetwork extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminManageNetwork
     */
    JPanel mainJpanel;
    Network rn;
    DMEcosystem es;
  //  private JPanel SystemAdminWorkAreaJPanel;
    
    public SystemAdminManageNetwork(JPanel jp,DMEcosystem es) {
        initComponents();
        rn=new Network();
        this.es=es;
        btnBack.setBorder(BorderFactory.createEmptyBorder());
      //  btnBack.getBorder().paintBorder(jp, g, WIDTH, WIDTH, WIDTH, HEIGHT);
        jScrollPane1.setBorder(BorderFactory.createEmptyBorder());
        this.mainJpanel=jp;
       // this.SystemAdminWorkAreaJPanel = SAW;
        PopulateTable("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNetworkName = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNetworkList = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Manage Network");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 292, 83));

        jLabel2.setText("Name :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 67, 32));
        add(txtNetworkName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 183, -1));

        btnEdit.setBackground(new java.awt.Color(0, 153, 255));
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 180, 112, 41));

        tblNetworkList.setAutoCreateRowSorter(true);
        tblNetworkList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Network Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNetworkList.setGridColor(new java.awt.Color(51, 102, 255));
        jScrollPane1.setViewportView(tblNetworkList);
        if (tblNetworkList.getColumnModel().getColumnCount() > 0) {
            tblNetworkList.getColumnModel().getColumn(0).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 368, 378));

        btnSave.setBackground(new java.awt.Color(0, 153, 255));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.setBorder(null);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 112, 41));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Double Left_100px.png"))); // NOI18N
        btnBack.setToolTipText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnBack.setBorderPainted(false);
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 105, 76));

        btnSearch.setBackground(new java.awt.Color(0, 153, 255));
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 110, 40));

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 190, -1));

        jLabel3.setText("Search Keyword: ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 110, 32));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        // TODO add your handling code here:
        
           btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Double Left_100px2.png")));
           btnBack.setBorderPainted(false);
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        // TODO add your handling code here:
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Double Left_100px.png")));
    }//GEN-LAST:event_btnBackMouseExited

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       
       mainJpanel.remove(this);
       CardLayout layout = (CardLayout) mainJpanel.getLayout();
        layout.previous(mainJpanel);

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
       if(txtNetworkName.getText().equals("")|| checkElement())
       {
           JOptionPane.showMessageDialog(null, "Network Name can not be blank or Duplicate");
       }
       else
       {
           if (btnSave.getText().equals("Update"))
            {
                btnSave.setText("Save");
                 AddNetwork(true);
                 JOptionPane.showMessageDialog(null, "Network added Successfully");
              
            }
            else
            {
                AddNetwork(false);
                JOptionPane.showMessageDialog(null, "Network added Successfully");

            }
        
            txtNetworkName.setText("");
       }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
          int selectedRow=tblNetworkList.getSelectedRow();
        if (selectedRow>=0)
        {
        
           rn=(Network)tblNetworkList.getValueAt(selectedRow,0);
           txtNetworkName.setText(rn.getName());
           btnSave.setText("Update");
          
           // resetTextfield();s
            
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Pleases select Row ");
        }
        
        
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        PopulateTable(txtSearch.getText());
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed
  
   public boolean checkElement()
    {
        Boolean B=false ;
        for(Network s : es.getNetworkList())
        {
           if(s.getName().equals(txtNetworkName.getText())) 
           {
               B= true;
               break;
           }
        }
        return B;
    }
    public void AddNetwork(Boolean IsUpdate)
    {
        String Name =txtNetworkName.getText();
     //   rn =new Network();
        
        if(!IsUpdate)
        {
            Network n =es.createAndAddNetwork();
            n.setName(Name);
           // es.addNetwork(n);
           
        }
        else 
        {
            rn.setName(Name);
        }
        PopulateTable("");
    }

    public void PopulateTable(String text)
    {
      
           DefaultTableModel DTM=(DefaultTableModel)tblNetworkList.getModel();
           DTM.setRowCount(0);
           for(Network ps: es.getNetworkList())
           {
                Object[] row  =new Object[1];
                row[0]=ps;
                if(ps.toString().contains(text)|| text=="")
                {
                        DTM.addRow(row); 
                }
           
           
           }
       
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNetworkList;
    private javax.swing.JTextField txtNetworkName;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
