/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author iamni
 */
public class RiskFactors extends javax.swing.JPanel {

    /**
     * Creates new form SWOTanalysis
     */
    public RiskFactors() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jrdMarketReach1 = new javax.swing.JRadioButton();
        jrdMarketReach2 = new javax.swing.JRadioButton();
        jrdMarketReach3 = new javax.swing.JRadioButton();
        jrdMarketReach4 = new javax.swing.JRadioButton();
        jrdMarketReach5 = new javax.swing.JRadioButton();
        lblFactors = new javax.swing.JLabel();
        lblRanking = new javax.swing.JLabel();
        txtMarketReach = new javax.swing.JTextField();
        jrdInnovativeAspects1 = new javax.swing.JRadioButton();
        jrdInnovativeAspects2 = new javax.swing.JRadioButton();
        jrdInnovativeAspects3 = new javax.swing.JRadioButton();
        jrdInnovativeAspects4 = new javax.swing.JRadioButton();
        jrdInnovativeAspects5 = new javax.swing.JRadioButton();
        txtInnovativeAspects = new javax.swing.JTextField();
        jrdProductDurability1 = new javax.swing.JRadioButton();
        jrdProductDurability2 = new javax.swing.JRadioButton();
        jrdProductDurability3 = new javax.swing.JRadioButton();
        jrdProductDurability4 = new javax.swing.JRadioButton();
        jrdProductDurability5 = new javax.swing.JRadioButton();
        txtProductDurability = new javax.swing.JTextField();
        lblComments = new javax.swing.JLabel();
        jrdCustomerAcceptance1 = new javax.swing.JRadioButton();
        jrdCustomerAcceptance2 = new javax.swing.JRadioButton();
        jrdCustomerAcceptance3 = new javax.swing.JRadioButton();
        jrdCustomerAcceptance4 = new javax.swing.JRadioButton();
        jrdCustomerAcceptance5 = new javax.swing.JRadioButton();
        txtCustomerAcceptance = new javax.swing.JTextField();
        jrdMarketDemand1 = new javax.swing.JRadioButton();
        jrdMarketDemand2 = new javax.swing.JRadioButton();
        jrdMarketDemand3 = new javax.swing.JRadioButton();
        jrdMarketDemand4 = new javax.swing.JRadioButton();
        jrdMarketDemand5 = new javax.swing.JRadioButton();
        txtMarketDemand = new javax.swing.JTextField();
        jrdTradeBarrier1 = new javax.swing.JRadioButton();
        jrdTradeBarrier2 = new javax.swing.JRadioButton();
        jrdTradeBarrier3 = new javax.swing.JRadioButton();
        jrdTradeBarrier4 = new javax.swing.JRadioButton();
        jrdTradeBarrier5 = new javax.swing.JRadioButton();
        txtTradeBarrier = new javax.swing.JTextField();
        jrdProductReach1 = new javax.swing.JRadioButton();
        jrdProductReach2 = new javax.swing.JRadioButton();
        jrdProductReach3 = new javax.swing.JRadioButton();
        jrdProductReach4 = new javax.swing.JRadioButton();
        jrdProductReach5 = new javax.swing.JRadioButton();
        txtProductReach = new javax.swing.JTextField();
        jrdFirstMover1 = new javax.swing.JRadioButton();
        jrdFirstMover2 = new javax.swing.JRadioButton();
        jrdFirstMover3 = new javax.swing.JRadioButton();
        jrdFirstMover4 = new javax.swing.JRadioButton();
        jrdFirstMover5 = new javax.swing.JRadioButton();
        txtFirstMover = new javax.swing.JTextField();
        lblFinanceCrunch = new javax.swing.JLabel();
        jrdProductDemand1 = new javax.swing.JRadioButton();
        jrdProductDemand2 = new javax.swing.JRadioButton();
        jrdProductDemand3 = new javax.swing.JRadioButton();
        jrdProductDemand4 = new javax.swing.JRadioButton();
        jrdProductDemand5 = new javax.swing.JRadioButton();
        txtProductDemand = new javax.swing.JTextField();
        jrdUSPproposition1 = new javax.swing.JRadioButton();
        jrdUSPproposition2 = new javax.swing.JRadioButton();
        jrdUSPproposition3 = new javax.swing.JRadioButton();
        jrdUSPproposition4 = new javax.swing.JRadioButton();
        jrdUSPproposition5 = new javax.swing.JRadioButton();
        txtUSPproposition = new javax.swing.JTextField();
        jrdFinanceCrunch1 = new javax.swing.JRadioButton();
        jrdFinanceCrunch2 = new javax.swing.JRadioButton();
        jrdFinanceCrunch3 = new javax.swing.JRadioButton();
        jrdFinanceCrunch4 = new javax.swing.JRadioButton();
        jrdFinanceCrunch5 = new javax.swing.JRadioButton();
        txtFinanceCrunch = new javax.swing.JTextField();
        lblProductDemand = new javax.swing.JLabel();
        lblMarketReach = new javax.swing.JLabel();
        lblInnovativeAspects = new javax.swing.JLabel();
        lblProductDurability = new javax.swing.JLabel();
        lblCustomerAcceptance = new javax.swing.JLabel();
        lblProductDemand6 = new javax.swing.JLabel();
        lblTradeBarrier = new javax.swing.JLabel();
        lblProductReach = new javax.swing.JLabel();
        lblFirstMover = new javax.swing.JLabel();
        lblUSPproposition = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 800));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Risk Factors");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 268, 70));

        jrdMarketReach1.setText("1");
        jrdMarketReach1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdMarketReach1ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdMarketReach1, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 206, -1, -1));

        jrdMarketReach2.setText("2");
        jrdMarketReach2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdMarketReach2ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdMarketReach2, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 206, -1, -1));

        jrdMarketReach3.setText("3");
        jrdMarketReach3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdMarketReach3ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdMarketReach3, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 206, -1, -1));

        jrdMarketReach4.setText("4");
        jrdMarketReach4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdMarketReach4ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdMarketReach4, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 206, -1, -1));

        jrdMarketReach5.setText("5");
        jrdMarketReach5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdMarketReach5ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdMarketReach5, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 206, -1, -1));

        lblFactors.setText("Factors");
        jPanel1.add(lblFactors, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 139, 94, 21));

        lblRanking.setText("Ranking ");
        jPanel1.add(lblRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 143, 73, -1));

        txtMarketReach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarketReachActionPerformed(evt);
            }
        });
        jPanel1.add(txtMarketReach, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 207, 168, -1));

        jrdInnovativeAspects1.setText("1");
        jrdInnovativeAspects1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdInnovativeAspects1ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdInnovativeAspects1, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 245, -1, -1));

        jrdInnovativeAspects2.setText("2");
        jrdInnovativeAspects2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdInnovativeAspects2ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdInnovativeAspects2, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 245, -1, -1));

        jrdInnovativeAspects3.setText("3");
        jrdInnovativeAspects3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdInnovativeAspects3ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdInnovativeAspects3, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 245, -1, -1));

        jrdInnovativeAspects4.setText("4");
        jrdInnovativeAspects4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdInnovativeAspects4ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdInnovativeAspects4, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 245, -1, -1));

        jrdInnovativeAspects5.setText("5");
        jrdInnovativeAspects5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdInnovativeAspects5ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdInnovativeAspects5, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 245, -1, -1));

        txtInnovativeAspects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInnovativeAspectsActionPerformed(evt);
            }
        });
        jPanel1.add(txtInnovativeAspects, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 246, 168, -1));

        jrdProductDurability1.setText("1");
        jrdProductDurability1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdProductDurability1ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdProductDurability1, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 284, -1, -1));

        jrdProductDurability2.setText("2");
        jrdProductDurability2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdProductDurability2ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdProductDurability2, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 284, -1, -1));

        jrdProductDurability3.setText("3");
        jrdProductDurability3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdProductDurability3ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdProductDurability3, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 284, -1, -1));

        jrdProductDurability4.setText("4");
        jrdProductDurability4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdProductDurability4ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdProductDurability4, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 284, -1, -1));

        jrdProductDurability5.setText("5");
        jrdProductDurability5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdProductDurability5ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdProductDurability5, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 284, -1, -1));

        txtProductDurability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductDurabilityActionPerformed(evt);
            }
        });
        jPanel1.add(txtProductDurability, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 285, 168, -1));

        lblComments.setText("Comments");
        jPanel1.add(lblComments, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 143, 73, -1));

        jrdCustomerAcceptance1.setText("1");
        jrdCustomerAcceptance1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdCustomerAcceptance1ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdCustomerAcceptance1, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 323, -1, -1));

        jrdCustomerAcceptance2.setText("2");
        jrdCustomerAcceptance2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdCustomerAcceptance2ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdCustomerAcceptance2, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 323, -1, -1));

        jrdCustomerAcceptance3.setText("3");
        jrdCustomerAcceptance3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdCustomerAcceptance3ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdCustomerAcceptance3, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 323, -1, -1));

        jrdCustomerAcceptance4.setText("4");
        jrdCustomerAcceptance4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdCustomerAcceptance4ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdCustomerAcceptance4, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 323, -1, -1));

        jrdCustomerAcceptance5.setText("5");
        jrdCustomerAcceptance5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdCustomerAcceptance5ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdCustomerAcceptance5, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 323, -1, -1));

        txtCustomerAcceptance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerAcceptanceActionPerformed(evt);
            }
        });
        jPanel1.add(txtCustomerAcceptance, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 324, 168, -1));

        jrdMarketDemand1.setText("1");
        jrdMarketDemand1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdMarketDemand1ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdMarketDemand1, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 362, -1, -1));

        jrdMarketDemand2.setText("2");
        jrdMarketDemand2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdMarketDemand2ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdMarketDemand2, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 362, -1, -1));

        jrdMarketDemand3.setText("3");
        jrdMarketDemand3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdMarketDemand3ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdMarketDemand3, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 362, -1, -1));

        jrdMarketDemand4.setText("4");
        jrdMarketDemand4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdMarketDemand4ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdMarketDemand4, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 362, -1, -1));

        jrdMarketDemand5.setText("5");
        jrdMarketDemand5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdMarketDemand5ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdMarketDemand5, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 362, -1, -1));

        txtMarketDemand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarketDemandActionPerformed(evt);
            }
        });
        jPanel1.add(txtMarketDemand, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 363, 168, -1));

        jrdTradeBarrier1.setText("1");
        jrdTradeBarrier1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdTradeBarrier1ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdTradeBarrier1, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 401, -1, -1));

        jrdTradeBarrier2.setText("2");
        jrdTradeBarrier2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdTradeBarrier2ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdTradeBarrier2, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 401, -1, -1));

        jrdTradeBarrier3.setText("3");
        jrdTradeBarrier3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdTradeBarrier3ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdTradeBarrier3, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 401, -1, -1));

        jrdTradeBarrier4.setText("4");
        jrdTradeBarrier4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdTradeBarrier4ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdTradeBarrier4, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 401, -1, -1));

        jrdTradeBarrier5.setText("5");
        jrdTradeBarrier5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdTradeBarrier5ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdTradeBarrier5, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 401, -1, -1));

        txtTradeBarrier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTradeBarrierActionPerformed(evt);
            }
        });
        jPanel1.add(txtTradeBarrier, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 402, 168, -1));

        jrdProductReach1.setText("1");
        jrdProductReach1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdProductReach1ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdProductReach1, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 440, -1, -1));

        jrdProductReach2.setText("2");
        jrdProductReach2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdProductReach2ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdProductReach2, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 440, -1, -1));

        jrdProductReach3.setText("3");
        jrdProductReach3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdProductReach3ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdProductReach3, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 440, -1, -1));

        jrdProductReach4.setText("4");
        jrdProductReach4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdProductReach4ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdProductReach4, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 440, -1, -1));

        jrdProductReach5.setText("5");
        jrdProductReach5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdProductReach5ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdProductReach5, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 440, -1, -1));

        txtProductReach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductReachActionPerformed(evt);
            }
        });
        jPanel1.add(txtProductReach, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 441, 168, -1));

        jrdFirstMover1.setText("1");
        jrdFirstMover1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdFirstMover1ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdFirstMover1, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 479, -1, -1));

        jrdFirstMover2.setText("2");
        jrdFirstMover2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdFirstMover2ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdFirstMover2, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 479, -1, -1));

        jrdFirstMover3.setText("3");
        jrdFirstMover3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdFirstMover3ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdFirstMover3, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 479, -1, -1));

        jrdFirstMover4.setText("4");
        jrdFirstMover4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdFirstMover4ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdFirstMover4, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 479, -1, -1));

        jrdFirstMover5.setText("5");
        jrdFirstMover5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdFirstMover5ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdFirstMover5, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 479, -1, -1));

        txtFirstMover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstMoverActionPerformed(evt);
            }
        });
        jPanel1.add(txtFirstMover, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, 168, -1));

        lblFinanceCrunch.setText("Finance Crunch:");
        jPanel1.add(lblFinanceCrunch, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, 120, 20));

        jrdProductDemand1.setText("1");
        jrdProductDemand1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdProductDemand1ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdProductDemand1, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 170, -1, -1));

        jrdProductDemand2.setText("2");
        jrdProductDemand2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdProductDemand2ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdProductDemand2, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 170, -1, -1));

        jrdProductDemand3.setText("3");
        jrdProductDemand3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdProductDemand3ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdProductDemand3, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 170, -1, -1));

        jrdProductDemand4.setText("4");
        jrdProductDemand4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdProductDemand4ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdProductDemand4, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 170, -1, -1));

        jrdProductDemand5.setText("5");
        jrdProductDemand5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdProductDemand5ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdProductDemand5, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 170, -1, -1));

        txtProductDemand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductDemandActionPerformed(evt);
            }
        });
        jPanel1.add(txtProductDemand, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 171, 168, -1));

        jrdUSPproposition1.setText("1");
        jrdUSPproposition1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdUSPproposition1ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdUSPproposition1, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 518, -1, -1));

        jrdUSPproposition2.setText("2");
        jrdUSPproposition2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdUSPproposition2ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdUSPproposition2, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 518, -1, -1));

        jrdUSPproposition3.setText("3");
        jrdUSPproposition3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdUSPproposition3ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdUSPproposition3, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 518, -1, -1));

        jrdUSPproposition4.setText("4");
        jrdUSPproposition4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdUSPproposition4ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdUSPproposition4, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 518, -1, -1));

        jrdUSPproposition5.setText("5");
        jrdUSPproposition5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdUSPproposition5ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdUSPproposition5, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 518, -1, -1));

        txtUSPproposition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUSPpropositionActionPerformed(evt);
            }
        });
        jPanel1.add(txtUSPproposition, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 519, 168, -1));

        jrdFinanceCrunch1.setText("1");
        jrdFinanceCrunch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdFinanceCrunch1ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdFinanceCrunch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 557, -1, -1));

        jrdFinanceCrunch2.setText("2");
        jrdFinanceCrunch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdFinanceCrunch2ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdFinanceCrunch2, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 557, -1, -1));

        jrdFinanceCrunch3.setText("3");
        jrdFinanceCrunch3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdFinanceCrunch3ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdFinanceCrunch3, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 557, -1, -1));

        jrdFinanceCrunch4.setText("4");
        jrdFinanceCrunch4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdFinanceCrunch4ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdFinanceCrunch4, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 557, -1, -1));

        jrdFinanceCrunch5.setText("5");
        jrdFinanceCrunch5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdFinanceCrunch5ActionPerformed(evt);
            }
        });
        jPanel1.add(jrdFinanceCrunch5, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 557, -1, -1));

        txtFinanceCrunch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFinanceCrunchActionPerformed(evt);
            }
        });
        jPanel1.add(txtFinanceCrunch, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 558, 168, -1));

        lblProductDemand.setText("Product Demand:");
        jPanel1.add(lblProductDemand, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 120, 20));

        lblMarketReach.setText("Market Reach:");
        jPanel1.add(lblMarketReach, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 120, 20));

        lblInnovativeAspects.setText("Innovative Aspects:");
        jPanel1.add(lblInnovativeAspects, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 120, 20));

        lblProductDurability.setText("Product Durability:");
        jPanel1.add(lblProductDurability, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 120, 20));

        lblCustomerAcceptance.setText("Customer Acceptance:");
        jPanel1.add(lblCustomerAcceptance, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 120, 20));

        lblProductDemand6.setText("Market Demand:");
        jPanel1.add(lblProductDemand6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 120, 20));

        lblTradeBarrier.setText("Trade Barrier:");
        jPanel1.add(lblTradeBarrier, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 120, 20));

        lblProductReach.setText("Product Reach:");
        jPanel1.add(lblProductReach, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 120, 20));

        lblFirstMover.setText("First Mover:");
        jPanel1.add(lblFirstMover, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 120, 20));

        lblUSPproposition.setText("USP Proposition:");
        jPanel1.add(lblUSPproposition, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 120, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jrdMarketReach1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdMarketReach1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdMarketReach1ActionPerformed

    private void jrdMarketReach2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdMarketReach2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdMarketReach2ActionPerformed

    private void jrdMarketReach3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdMarketReach3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdMarketReach3ActionPerformed

    private void jrdMarketReach4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdMarketReach4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdMarketReach4ActionPerformed

    private void jrdMarketReach5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdMarketReach5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdMarketReach5ActionPerformed

    private void txtMarketReachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarketReachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarketReachActionPerformed

    private void jrdInnovativeAspects1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdInnovativeAspects1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdInnovativeAspects1ActionPerformed

    private void jrdInnovativeAspects2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdInnovativeAspects2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdInnovativeAspects2ActionPerformed

    private void jrdInnovativeAspects3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdInnovativeAspects3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdInnovativeAspects3ActionPerformed

    private void jrdInnovativeAspects4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdInnovativeAspects4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdInnovativeAspects4ActionPerformed

    private void jrdInnovativeAspects5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdInnovativeAspects5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdInnovativeAspects5ActionPerformed

    private void txtInnovativeAspectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInnovativeAspectsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInnovativeAspectsActionPerformed

    private void jrdProductDurability1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdProductDurability1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdProductDurability1ActionPerformed

    private void jrdProductDurability2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdProductDurability2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdProductDurability2ActionPerformed

    private void jrdProductDurability3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdProductDurability3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdProductDurability3ActionPerformed

    private void jrdProductDurability4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdProductDurability4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdProductDurability4ActionPerformed

    private void jrdProductDurability5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdProductDurability5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdProductDurability5ActionPerformed

    private void txtProductDurabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductDurabilityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductDurabilityActionPerformed

    private void jrdCustomerAcceptance1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdCustomerAcceptance1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdCustomerAcceptance1ActionPerformed

    private void jrdCustomerAcceptance2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdCustomerAcceptance2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdCustomerAcceptance2ActionPerformed

    private void jrdCustomerAcceptance3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdCustomerAcceptance3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdCustomerAcceptance3ActionPerformed

    private void jrdCustomerAcceptance4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdCustomerAcceptance4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdCustomerAcceptance4ActionPerformed

    private void jrdCustomerAcceptance5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdCustomerAcceptance5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdCustomerAcceptance5ActionPerformed

    private void txtCustomerAcceptanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerAcceptanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerAcceptanceActionPerformed

    private void jrdMarketDemand1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdMarketDemand1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdMarketDemand1ActionPerformed

    private void jrdMarketDemand2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdMarketDemand2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdMarketDemand2ActionPerformed

    private void jrdMarketDemand3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdMarketDemand3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdMarketDemand3ActionPerformed

    private void jrdMarketDemand4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdMarketDemand4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdMarketDemand4ActionPerformed

    private void jrdMarketDemand5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdMarketDemand5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdMarketDemand5ActionPerformed

    private void txtMarketDemandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarketDemandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarketDemandActionPerformed

    private void jrdTradeBarrier1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdTradeBarrier1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdTradeBarrier1ActionPerformed

    private void jrdTradeBarrier2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdTradeBarrier2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdTradeBarrier2ActionPerformed

    private void jrdTradeBarrier3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdTradeBarrier3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdTradeBarrier3ActionPerformed

    private void jrdTradeBarrier4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdTradeBarrier4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdTradeBarrier4ActionPerformed

    private void jrdTradeBarrier5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdTradeBarrier5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdTradeBarrier5ActionPerformed

    private void txtTradeBarrierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTradeBarrierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTradeBarrierActionPerformed

    private void jrdProductReach1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdProductReach1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdProductReach1ActionPerformed

    private void jrdProductReach2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdProductReach2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdProductReach2ActionPerformed

    private void jrdProductReach3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdProductReach3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdProductReach3ActionPerformed

    private void jrdProductReach4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdProductReach4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdProductReach4ActionPerformed

    private void jrdProductReach5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdProductReach5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdProductReach5ActionPerformed

    private void txtProductReachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductReachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductReachActionPerformed

    private void jrdFirstMover1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdFirstMover1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdFirstMover1ActionPerformed

    private void jrdFirstMover2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdFirstMover2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdFirstMover2ActionPerformed

    private void jrdFirstMover3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdFirstMover3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdFirstMover3ActionPerformed

    private void jrdFirstMover4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdFirstMover4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdFirstMover4ActionPerformed

    private void jrdFirstMover5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdFirstMover5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdFirstMover5ActionPerformed

    private void txtFirstMoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstMoverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstMoverActionPerformed

    private void jrdProductDemand1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdProductDemand1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdProductDemand1ActionPerformed

    private void jrdProductDemand2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdProductDemand2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdProductDemand2ActionPerformed

    private void jrdProductDemand3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdProductDemand3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdProductDemand3ActionPerformed

    private void jrdProductDemand4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdProductDemand4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdProductDemand4ActionPerformed

    private void jrdProductDemand5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdProductDemand5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdProductDemand5ActionPerformed

    private void txtProductDemandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductDemandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductDemandActionPerformed

    private void jrdUSPproposition1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdUSPproposition1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdUSPproposition1ActionPerformed

    private void jrdUSPproposition2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdUSPproposition2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdUSPproposition2ActionPerformed

    private void jrdUSPproposition3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdUSPproposition3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdUSPproposition3ActionPerformed

    private void jrdUSPproposition4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdUSPproposition4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdUSPproposition4ActionPerformed

    private void jrdUSPproposition5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdUSPproposition5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdUSPproposition5ActionPerformed

    private void txtUSPpropositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUSPpropositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUSPpropositionActionPerformed

    private void jrdFinanceCrunch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdFinanceCrunch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdFinanceCrunch1ActionPerformed

    private void jrdFinanceCrunch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdFinanceCrunch2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdFinanceCrunch2ActionPerformed

    private void jrdFinanceCrunch3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdFinanceCrunch3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdFinanceCrunch3ActionPerformed

    private void jrdFinanceCrunch4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdFinanceCrunch4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdFinanceCrunch4ActionPerformed

    private void jrdFinanceCrunch5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdFinanceCrunch5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdFinanceCrunch5ActionPerformed

    private void txtFinanceCrunchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFinanceCrunchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFinanceCrunchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jrdCustomerAcceptance1;
    private javax.swing.JRadioButton jrdCustomerAcceptance2;
    private javax.swing.JRadioButton jrdCustomerAcceptance3;
    private javax.swing.JRadioButton jrdCustomerAcceptance4;
    private javax.swing.JRadioButton jrdCustomerAcceptance5;
    private javax.swing.JRadioButton jrdFinanceCrunch1;
    private javax.swing.JRadioButton jrdFinanceCrunch2;
    private javax.swing.JRadioButton jrdFinanceCrunch3;
    private javax.swing.JRadioButton jrdFinanceCrunch4;
    private javax.swing.JRadioButton jrdFinanceCrunch5;
    private javax.swing.JRadioButton jrdFirstMover1;
    private javax.swing.JRadioButton jrdFirstMover2;
    private javax.swing.JRadioButton jrdFirstMover3;
    private javax.swing.JRadioButton jrdFirstMover4;
    private javax.swing.JRadioButton jrdFirstMover5;
    private javax.swing.JRadioButton jrdInnovativeAspects1;
    private javax.swing.JRadioButton jrdInnovativeAspects2;
    private javax.swing.JRadioButton jrdInnovativeAspects3;
    private javax.swing.JRadioButton jrdInnovativeAspects4;
    private javax.swing.JRadioButton jrdInnovativeAspects5;
    private javax.swing.JRadioButton jrdMarketDemand1;
    private javax.swing.JRadioButton jrdMarketDemand2;
    private javax.swing.JRadioButton jrdMarketDemand3;
    private javax.swing.JRadioButton jrdMarketDemand4;
    private javax.swing.JRadioButton jrdMarketDemand5;
    private javax.swing.JRadioButton jrdMarketReach1;
    private javax.swing.JRadioButton jrdMarketReach2;
    private javax.swing.JRadioButton jrdMarketReach3;
    private javax.swing.JRadioButton jrdMarketReach4;
    private javax.swing.JRadioButton jrdMarketReach5;
    private javax.swing.JRadioButton jrdProductDemand1;
    private javax.swing.JRadioButton jrdProductDemand2;
    private javax.swing.JRadioButton jrdProductDemand3;
    private javax.swing.JRadioButton jrdProductDemand4;
    private javax.swing.JRadioButton jrdProductDemand5;
    private javax.swing.JRadioButton jrdProductDurability1;
    private javax.swing.JRadioButton jrdProductDurability2;
    private javax.swing.JRadioButton jrdProductDurability3;
    private javax.swing.JRadioButton jrdProductDurability4;
    private javax.swing.JRadioButton jrdProductDurability5;
    private javax.swing.JRadioButton jrdProductReach1;
    private javax.swing.JRadioButton jrdProductReach2;
    private javax.swing.JRadioButton jrdProductReach3;
    private javax.swing.JRadioButton jrdProductReach4;
    private javax.swing.JRadioButton jrdProductReach5;
    private javax.swing.JRadioButton jrdTradeBarrier1;
    private javax.swing.JRadioButton jrdTradeBarrier2;
    private javax.swing.JRadioButton jrdTradeBarrier3;
    private javax.swing.JRadioButton jrdTradeBarrier4;
    private javax.swing.JRadioButton jrdTradeBarrier5;
    private javax.swing.JRadioButton jrdUSPproposition1;
    private javax.swing.JRadioButton jrdUSPproposition2;
    private javax.swing.JRadioButton jrdUSPproposition3;
    private javax.swing.JRadioButton jrdUSPproposition4;
    private javax.swing.JRadioButton jrdUSPproposition5;
    private javax.swing.JLabel lblComments;
    private javax.swing.JLabel lblCustomerAcceptance;
    private javax.swing.JLabel lblFactors;
    private javax.swing.JLabel lblFinanceCrunch;
    private javax.swing.JLabel lblFirstMover;
    private javax.swing.JLabel lblInnovativeAspects;
    private javax.swing.JLabel lblMarketReach;
    private javax.swing.JLabel lblProductDemand;
    private javax.swing.JLabel lblProductDemand6;
    private javax.swing.JLabel lblProductDurability;
    private javax.swing.JLabel lblProductReach;
    private javax.swing.JLabel lblRanking;
    private javax.swing.JLabel lblTradeBarrier;
    private javax.swing.JLabel lblUSPproposition;
    private javax.swing.JTextField txtCustomerAcceptance;
    private javax.swing.JTextField txtFinanceCrunch;
    private javax.swing.JTextField txtFirstMover;
    private javax.swing.JTextField txtInnovativeAspects;
    private javax.swing.JTextField txtMarketDemand;
    private javax.swing.JTextField txtMarketReach;
    private javax.swing.JTextField txtProductDemand;
    private javax.swing.JTextField txtProductDurability;
    private javax.swing.JTextField txtProductReach;
    private javax.swing.JTextField txtTradeBarrier;
    private javax.swing.JTextField txtUSPproposition;
    // End of variables declaration//GEN-END:variables
}
