/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author iamni
 */
public class SendSMS extends javax.swing.JPanel {

    /**
     * Creates new form SendSMS
     */
    public SendSMS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRecEmailAddr = new javax.swing.JLabel();
        txtRecPhnNum = new javax.swing.JTextField();
        lblEmailBody = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMsgBody = new javax.swing.JTextArea();
        btnSend = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRecEmailAddr.setText("Recepient Phone Number:");
        add(lblRecEmailAddr, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 120, 30));
        add(txtRecPhnNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 240, 30));

        lblEmailBody.setText("Message Body:");
        add(lblEmailBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 120, -1));

        txtMsgBody.setColumns(20);
        txtMsgBody.setRows(5);
        jScrollPane1.setViewportView(txtMsgBody);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 240, 87));

        btnSend.setBackground(new java.awt.Color(0, 153, 255));
        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        add(btnSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 150, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        //Enterprise enterprise = (Enterprise) enterpriseJComboBox.getSelectedItem();
    }//GEN-LAST:event_btnSendActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEmailBody;
    private javax.swing.JLabel lblRecEmailAddr;
    private javax.swing.JTextArea txtMsgBody;
    private javax.swing.JTextField txtRecPhnNum;
    // End of variables declaration//GEN-END:variables
}
