/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author iamni
 */
public class SendEmail extends javax.swing.JPanel {

    /**
     * Creates new form SendEmail
     */
    public SendEmail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRecEmailAddr = new javax.swing.JLabel();
        txtRecEmailAdd = new javax.swing.JTextField();
        lblSubject = new javax.swing.JLabel();
        txtSubject = new javax.swing.JTextField();
        lblEmailBody = new javax.swing.JLabel();
        lblAttachment = new javax.swing.JLabel();
        txtAttachment = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        thtAreaEmailBody = new javax.swing.JTextArea();
        btnSend = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRecEmailAddr.setText("Recepient Email Address:");
        add(lblRecEmailAddr, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 120, 30));
        add(txtRecEmailAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 240, 30));

        lblSubject.setText("Subject:");
        add(lblSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 120, -1));
        add(txtSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 240, 30));

        lblEmailBody.setText("Email Body:");
        add(lblEmailBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 120, -1));

        lblAttachment.setText("Attachment:");
        add(lblAttachment, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 120, -1));
        add(txtAttachment, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 240, 30));

        thtAreaEmailBody.setColumns(20);
        thtAreaEmailBody.setRows(5);
        jScrollPane1.setViewportView(thtAreaEmailBody);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 240, 87));

        btnSend.setBackground(new java.awt.Color(0, 153, 255));
        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        add(btnSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 150, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 470, 370));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        //Enterprise enterprise = (Enterprise) enterpriseJComboBox.getSelectedItem();

    }//GEN-LAST:event_btnSendActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAttachment;
    private javax.swing.JLabel lblEmailBody;
    private javax.swing.JLabel lblRecEmailAddr;
    private javax.swing.JLabel lblSubject;
    private javax.swing.JTextArea thtAreaEmailBody;
    private javax.swing.JPasswordField txtAttachment;
    private javax.swing.JTextField txtRecEmailAdd;
    private javax.swing.JTextField txtSubject;
    // End of variables declaration//GEN-END:variables
}
