/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.socialMediaSpeciaList;

import Business.DMEcosystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.marketAnalystOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import Business.WorkQueue.productDetailWorkRequest;
import UserInterface.ProductAnalystRole.ProductAnalystProductDetailsJpanel;
import java.awt.CardLayout;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import twitter4j.TwitterException;

/**
 *
 * @author dhava
 */
public class socialmediaSpecialitsWorkListJPanel extends javax.swing.JPanel {

    /**
     * Creates new form socialmediaSpecialitsWorkListJPanel
     */
   JPanel userProcessContainer;
   UserAccount account;
   //productManagerOrganization  organization;
   Organization  organization;
   Enterprise enterprise;
   DMEcosystem business;
    public socialmediaSpecialitsWorkListJPanel(JPanel userProcessContainer,UserAccount account,Organization organization,Enterprise enterprise,DMEcosystem business) {
        initComponents();
         this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.organization=organization;
        this.enterprise=enterprise;
        this.business=business;
         populateRequestTable();
        
        
        
    }
 public void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel) tbltasklist.getModel();
        
        model.setRowCount(0);
        
      //  for (Organization o :enterprise.getOrganizationDirectory().getOrganizationList()) {
      for (Organization O:enterprise.getOrganizationDirectory().getOrganizationList())
      {
            for (WorkRequest request :O.getWorkQueue().getWorkRequestList())
            {  
                    Object[] row = new Object[4];
                    row[0] = request;
                    row[1] = request.getTitle();

          //  row[1] = ()request.;
          //  row[2] = o.;
          //  row[3] = request.getDuedate();
                
             if(request.getAssignto() == account.getEmployee())   
                   {
                       model.addRow(row);
                   }
                
            }
      }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbltasklist = new javax.swing.JTable();
        btnManageTask = new javax.swing.JButton();
        btnManageTask1 = new javax.swing.JButton();
        btnManageTask2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbltasklist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TaskID", "TaskName"
            }
        ));
        jScrollPane1.setViewportView(tbltasklist);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 220, 570, 303));

        btnManageTask.setBackground(new java.awt.Color(61, 99, 210));
        btnManageTask.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnManageTask.setForeground(new java.awt.Color(255, 255, 255));
        btnManageTask.setText("Send SMS");
        btnManageTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageTaskActionPerformed(evt);
            }
        });
        add(btnManageTask, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 390, 210, 60));

        btnManageTask1.setBackground(new java.awt.Color(61, 99, 210));
        btnManageTask1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnManageTask1.setForeground(new java.awt.Color(255, 255, 255));
        btnManageTask1.setText("Tweet");
        btnManageTask1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageTask1ActionPerformed(evt);
            }
        });
        add(btnManageTask1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, 210, 60));

        btnManageTask2.setBackground(new java.awt.Color(61, 99, 210));
        btnManageTask2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnManageTask2.setForeground(new java.awt.Color(255, 255, 255));
        btnManageTask2.setText("Send Email");
        btnManageTask2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageTask2ActionPerformed(evt);
            }
        });
        add(btnManageTask2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, 210, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageTaskActionPerformed
        // TODO add your handling code here:

//        socialMediasManagerworklistJPanel smn=new socialMediasManagerworklistJPanel(userProcessContainer,account,enterprise);
//        CardLayout cl=(CardLayout)userProcessContainer.getLayout();
//        userProcessContainer.add("socialMediasManagerworklistJPanel",smn);
//        cl.next(userProcessContainer);
    }//GEN-LAST:event_btnManageTaskActionPerformed

    private void btnManageTask1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageTask1ActionPerformed
        // TODO add your handling code here:
        
        
         int selectedRow=tbltasklist.getSelectedRow();
        if (selectedRow>=0)
        {
            
            WorkRequest en=(WorkRequest)tbltasklist.getValueAt(selectedRow,0);
            en.setStatus("In Process Digital Marketing Team");
            TwitterjPanel smn;
             try {
                 smn = new TwitterjPanel(userProcessContainer,account,en,enterprise);
                  CardLayout cl=(CardLayout)userProcessContainer.getLayout();
               userProcessContainer.add("TwitterjPanel",smn);
             cl.next(userProcessContainer);
             } catch (TwitterException ex) {
                 Logger.getLogger(socialmediaSpecialitsWorkListJPanel.class.getName()).log(Level.SEVERE, null, ex);
             }
          
           // resetTextfield();
            
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Pleases select Row ");
        }
      
    }//GEN-LAST:event_btnManageTask1ActionPerformed

    private void btnManageTask2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageTask2ActionPerformed
        // TODO add your handling code here:
           int selectedRow=tbltasklist.getSelectedRow();
        if (selectedRow>=0)
        {
            
            WorkRequest en=(WorkRequest)tbltasklist.getValueAt(selectedRow,0);
            en.setStatus("In Process Digital Marketing Team");
         
               try {
                      SendEmail  smn;
                   smn = new SendEmail(userProcessContainer,account,en,enterprise);
                     CardLayout cl=(CardLayout)userProcessContainer.getLayout();
               userProcessContainer.add("SendEmail",smn);
             cl.next(userProcessContainer);
               } catch (IOException ex) {
                   Logger.getLogger(socialmediaSpecialitsWorkListJPanel.class.getName()).log(Level.SEVERE, null, ex);
               }
                
        
          
           // resetTextfield();
            
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Pleases select Row ");
        }
      
        
    }//GEN-LAST:event_btnManageTask2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageTask;
    private javax.swing.JButton btnManageTask1;
    private javax.swing.JButton btnManageTask2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbltasklist;
    // End of variables declaration//GEN-END:variables
}
