/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.socialMediaSpeciaList;

import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import twitter4j.Twitter;
import twitter4j.TwitterException;
import twitter4j.TwitterFactory;
import twitter4j.auth.AccessToken;

/**
 *
 * @author dhava
 */
public class TwitterjPanel extends javax.swing.JPanel {

    /**
     * Creates new form TwitterjPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    WorkRequest request;
    Enterprise enterprise;
    public TwitterjPanel(JPanel userProcessContainer,UserAccount account,WorkRequest request,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.request=request;
        this.enterprise=enterprise;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txttwitter = new javax.swing.JTextArea();
        btnproceed = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txttwitter.setColumns(20);
        txttwitter.setRows(5);
        txttwitter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttwitterKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txttwitter);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 440, 280));

        btnproceed.setBackground(new java.awt.Color(0, 153, 255));
        btnproceed.setText("Tweet");
        btnproceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproceedActionPerformed(evt);
            }
        });
        add(btnproceed, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 150, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tweet"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, -1, 280));
    }// </editor-fold>//GEN-END:initComponents

    private void btnproceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproceedActionPerformed
        // TODO add your handling code here:
        //Enterprise enterprise = (Enterprise) enterpriseJComboBox.getSelectedItem();
      String consumerKeyStr = enterprise.getConsumerkey();//"zpGL6kU6RKXoHE7MYkX1hsS5u";
 
        //Your Twitter App's Consumer Secret
        String consumerSecretStr = enterprise.getConsumerSecretkey();//"KtubqX7OqHxZm79F9CeeeU9z7EXCaKOYtAVFIrflsgcr1wSFUL";
 
        //Your Twitter Access Token
        String accessTokenStr = enterprise.getAccessToken();//"1114998612692545550-TRf6N9YGy2SrD8cE7dlriQSCLjErCL";
 
        //Your Twitter Access Token Secret
        String accessTokenSecretStr = enterprise.getAccessTokenSecret();//"5687xOyIqQzw3CHes45fvKIOMEgACoXmjcRWZLGSnqa1m";
            
        Twitter twitter = new TwitterFactory().getInstance();

			twitter.setOAuthConsumer(consumerKeyStr, consumerSecretStr);
			AccessToken accessToken = new AccessToken(accessTokenStr,
					accessTokenSecretStr);

			twitter.setOAuthAccessToken(accessToken);

        try {
            
            
            if (txttwitter.getText().length()>250)
            {
            JOptionPane.showMessageDialog(null, "You cant write more than 250 words");
            return;
            }
            else
            {
                twitter.updateStatus(txttwitter.getText());
            }
            
        } catch (TwitterException ex) {
           // Logger.getLogger(TwitterjPanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Something went wrong in Connection");
            return;
        }

    }//GEN-LAST:event_btnproceedActionPerformed

    private void txttwitterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttwitterKeyPressed
        // TODO add your handling code here:
        if (txttwitter.getText().length()>250)
        {
            JOptionPane.showMessageDialog(null, "You cant write more than 250 words");
            return;
        }
        
    }//GEN-LAST:event_txttwitterKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnproceed;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea txttwitter;
    // End of variables declaration//GEN-END:variables
}
