/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ProductManagerRole;

import Business.WorkQueue.TwitterData;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Map;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dhava
 */
public class TwitterDetailCommentsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TwitterDetailCommentsJPanel
     */
    TwitterData TD;
    JPanel userProcessContainer;
    public TwitterDetailCommentsJPanel(JPanel userProcessContainer,TwitterData TD) {
        initComponents();
        this.TD=TD;
        this.userProcessContainer=userProcessContainer;
        if(TD!= null) 
        {
            txtTweet.setText(TD.getText()); 
            PopulateTable();
        }
        
    }

    
    public void PopulateTable()
    {
        
        
        DefaultTableModel model = (DefaultTableModel) tbltweetComments.getModel();
         model.setRowCount(0);
        
     for (Map.Entry<String, String>  comment: TD.getComments().entrySet()){
           
                    Object[] row = new Object[2];
                   // row[0] = request;
                    row[0] = comment.getKey();
                    row[1] = comment.getValue();
                    
                    model.addRow(row);
                  
            
        }   
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbltweetComments = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTweet = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Tweet Comments");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 268, 70));

        tbltweetComments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Comments", "Sentiments"
            }
        ));
        jScrollPane1.setViewportView(tbltweetComments);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, -1, 330));

        txtTweet.setColumns(20);
        txtTweet.setRows(5);
        txtTweet.setEnabled(false);
        jScrollPane2.setViewportView(txtTweet);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 390, 290));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Tweet ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 100, -1));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Double Left_100px.png"))); // NOI18N
        btnBack.setToolTipText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnBack.setBorderPainted(false);
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 105, 76));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        // TODO add your handling code here:

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Double Left_100px2.png")));
        btnBack.setBorderPainted(false);
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        // TODO add your handling code here:
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Double Left_100px.png")));
    }//GEN-LAST:event_btnBackMouseExited

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbltweetComments;
    private javax.swing.JTextArea txtTweet;
    // End of variables declaration//GEN-END:variables
}
