/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ProductManagerRole;

import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import twitter4j.Status;
import twitter4j.Twitter;
import twitter4j.TwitterException;
import twitter4j.TwitterFactory;
import twitter4j.auth.AccessToken;

/**
 *
 * @author dhava
 */
public class TwitterAnalysis extends javax.swing.JPanel {

    /**
     * Creates new form TwitterAnalysis
     */
    
     JPanel userProcessContainer;
   UserAccount account;
   private javax.swing.JTable tbltasklist;
    private javax.swing.JScrollPane jScrollPane1;
     String consumerKeyStr = "";
    String consumerSecretStr ="";
    String accessTokenStr = "";
    String accessTokenSecretStr ="";
   Enterprise enterprise;
    public TwitterAnalysis( JPanel userProcessContainer,UserAccount account ,Enterprise enterprise) throws TwitterException {
        initComponents();
          this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.enterprise=enterprise;
        jScrollPane1 = new javax.swing.JScrollPane();
        this.enterprise=enterprise;
        
         consumerKeyStr = enterprise.getConsumerkey();//"zpGL6kU6RKXoHE7MYkX1hsS5u";
 
          //Your Twitter App's Consumer Secret
         consumerSecretStr = enterprise.getConsumerSecretkey();//"KtubqX7OqHxZm79F9CeeeU9z7EXCaKOYtAVFIrflsgcr1wSFUL";
 
        //Your Twitter Access Token
         accessTokenStr = enterprise.getAccessToken();//"1114998612692545550-TRf6N9YGy2SrD8cE7dlriQSCLjErCL";
 
        //Your Twitter Access Token Secret
         accessTokenSecretStr = enterprise.getAccessTokenSecret();//"5687xOyIqQzw3CHes45fvKIOMEgACoXmjcRWZLGSnqa1m";
         populateRequestTable();
    }

    
    public void populateRequestTable() throws TwitterException{
        DefaultTableModel model = (DefaultTableModel) tbltweets.getModel();
             Twitter twitter = new TwitterFactory().getInstance();

			twitter.setOAuthConsumer(consumerKeyStr, consumerSecretStr);
			AccessToken accessToken = new AccessToken(accessTokenStr,
					accessTokenSecretStr);

			twitter.setOAuthAccessToken(accessToken);
        model.setRowCount(0);
        List<Status> statuses = twitter.getHomeTimeline(); 
      //  for (Organization o :enterprise.getOrganizationDirectory().getOrganizationList()) {
 
         for ( Status s :statuses) {
              Object[] row = new Object[4];
                    row[0] = s.getText();
                    row[1] = s.getRetweetCount();
                     model.addRow(row);
        }

          //  row[1] = ()request.;
          //  row[2] = o.;
          //  row[3] = request.getDuedate();
                
             
      
   }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tbltweets = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 800));

        tbltweets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tweet", "RetweetCount", "Comment", "Sentiments"
            }
        ));
        jScrollPane2.setViewportView(tbltweets);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Twitter Sentiment Analysis");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(367, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(59, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 861, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(92, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel1)
                .addContainerGap(546, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(185, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(185, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbltweets;
    // End of variables declaration//GEN-END:variables
}
