package UserInterface.ProductAnalystRole;


import Business.WorkQueue.productDetailWorkRequest;
import java.io.File;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.text.MaskFormatter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author iamni
 */
public class ProductAnalystProductDetailsJpanel extends javax.swing.JPanel {

    
  //s   private static final DateFormat df = new SimpleDateFormat("yyyy/mm/dd");
     JPanel userProcessContainer;
     productDetailWorkRequest request;
      ArrayList<String> FilePath =new ArrayList<String>();
    /**
     * Creates new form ProductDetails
     */
    public ProductAnalystProductDetailsJpanel(JPanel userProcessContainer,productDetailWorkRequest request) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.request=request;
         txtExpireddate.setColumns(20);
         txtmanufecturedate.setColumns(20);
        //panel.add(tf);
        try {
           //  JFormattedTextField tf = new JFormattedTextField();

            MaskFormatter dateMask = new MaskFormatter("##/##/####");
            dateMask.install(txtExpireddate);
            dateMask.install(txtmanufecturedate);
        } catch (ParseException ex) {
                return;
//Logger.getLogger(MaskFormatter.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtmarket = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSubmitProductDetails = new javax.swing.JButton();
        txtdurability = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtretailprice = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnSelectphoto = new javax.swing.JButton();
        txtmanufecturedate = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtfinalremark = new javax.swing.JTextArea();
        txtExpireddate = new javax.swing.JFormattedTextField();
        txtfeatures = new javax.swing.JTextField();
        txtlastrevenue = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Product Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 268, 80));

        jLabel5.setText("Product Name :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 120, 30));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 240, 30));

        jLabel2.setText("Market :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 120, 20));
        add(txtmarket, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 240, 30));

        jLabel4.setText("Features :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 120, -1));

        jLabel3.setText("Last Revenue :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 120, -1));

        btnSubmitProductDetails.setBackground(new java.awt.Color(0, 153, 255));
        btnSubmitProductDetails.setText("Submit Product Details");
        btnSubmitProductDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitProductDetailsActionPerformed(evt);
            }
        });
        add(btnSubmitProductDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 570, 260, 50));
        add(txtdurability, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 240, 30));

        jLabel9.setText("Durability :");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 120, 20));
        add(txtretailprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, 240, 30));

        jLabel10.setText("Manufacture Date :");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 150, 40));

        jLabel11.setText("Expired Date :");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 120, -1));

        jLabel12.setText("Final Remark :");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 120, -1));

        jLabel13.setText("Product Image :");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 120, -1));

        jLabel14.setText("Retail Price :");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 120, 20));

        btnSelectphoto.setText("Select Photo");
        btnSelectphoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectphotoActionPerformed(evt);
            }
        });
        add(btnSelectphoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 240, 30));
        add(txtmanufecturedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 296, 240, 30));

        txtfinalremark.setColumns(20);
        txtfinalremark.setRows(5);
        jScrollPane1.setViewportView(txtfinalremark);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, 240, -1));

        txtExpireddate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExpireddateActionPerformed(evt);
            }
        });
        add(txtExpireddate, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 240, 30));
        add(txtfeatures, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 276, 240, 30));
        add(txtlastrevenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 240, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitProductDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitProductDetailsActionPerformed
        // TODO add your handling code here:
        //Enterprise enterprise = (Enterprise) enterpriseJComboBox.getSelectedItem();
        if(! CheckNumber("Retail Price Respirate", txtretailprice.getText()) 
           || !CheckNumber("Last Revenue", txtlastrevenue.getText())
           )
            {
             return;
            }
        else
            {
            try {
                saveProductDetails();
                JOptionPane.showMessageDialog(null,"Product detail saved successfully..!!");
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null, "Something went wrong while saving data ..!!", "", JOptionPane.WARNING_MESSAGE);
                    return ;

//Logger.getLogger(ProductAnalystProductDetailsJpanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
    

    }//GEN-LAST:event_btnSubmitProductDetailsActionPerformed

    private void btnSelectphotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectphotoActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc =new JFileChooser();
        jfc.setMultiSelectionEnabled(true);
        jfc.setCurrentDirectory(new File("C:\\Users\\dhava\\OneDrive\\Desktop\\Certificates"));
        int showOpenDialog = jfc.showOpenDialog(null);
        String  FileName="";
        String[] FileFormat= {"jpg","png","jpeg"};
        Boolean isCorrect =false;
        int i=jfc. getSelectedFiles().length-1;
        
//  jfc.getSelectedFile().getName()

        while (showOpenDialog==JFileChooser.APPROVE_OPTION && jfc.getSelectedFile().getName() != null) {
            isCorrect =false;
            FileName=jfc.getSelectedFile().getName();

            for(String s : FileFormat)
            {
                if(FileName.endsWith(s))
                {
                    isCorrect=true;
                    break;
                }

            }

            if (!isCorrect) {
                JOptionPane.showMessageDialog(null, "The file "
                    + jfc.getSelectedFile() + " is not valid Image file",
                    "Open Error", JOptionPane.ERROR_MESSAGE);
                showOpenDialog = jfc.showOpenDialog(null);
            }else {

                FilePath.add(jfc.getSelectedFiles()[i].getPath()) ;
             //   filepath=jfc.getSelectedFile().getPath();
               // lblfilepath.setText(FileName);
                break;
            }
            i--;
        }

    }//GEN-LAST:event_btnSelectphotoActionPerformed

     public Boolean CheckNumber(String Name, String value) {

        try {
            Integer.parseInt(value);
            return true;

        } catch (NumberFormatException NE) {
            JOptionPane.showMessageDialog(null, "Please input a valid number for " + Name + "!", "", JOptionPane.WARNING_MESSAGE);
            return false;
        }

    }
    public void saveProductDetails() throws ParseException
    {
       String productName =txtName.getText();
       String market =txtmarket.getText();
       String Features =txtfeatures.getText();
       String LastRevenue =txtlastrevenue.getText();
       String Durability =txtdurability.getText();
       String RetailPrice =txtretailprice.getText();
       Date ManufectureDate = new SimpleDateFormat("dd/MM/yyyy").parse(txtExpireddate.getText());
       Date ExpiredDate =  new SimpleDateFormat("dd/MM/yyyy").parse(txtExpireddate.getText());
       String finalremark =txtfinalremark.getText();
 
       request.setProductName(productName);
       request.setMarket(market);
       request.setFeature(Features);
       request.setLastRevenue(LastRevenue);
       request.setDurability(Durability);
       request.setReatilPrice(Integer.valueOf(RetailPrice));
       request.setManufectureDate(ManufectureDate);
       request.setExpiredate(ExpiredDate);
       request.setFinalRemark(finalremark);
       request.setProductImages(FilePath);
       request.setStatus("Completed by Product Analyst");
    
    }
    
    
    
    
    
    
    private void txtExpireddateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExpireddateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExpireddateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelectphoto;
    private javax.swing.JButton btnSubmitProductDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField txtExpireddate;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtdurability;
    private javax.swing.JTextField txtfeatures;
    private javax.swing.JTextArea txtfinalremark;
    private javax.swing.JTextField txtlastrevenue;
    private javax.swing.JFormattedTextField txtmanufecturedate;
    private javax.swing.JTextField txtmarket;
    private javax.swing.JTextField txtretailprice;
    // End of variables declaration//GEN-END:variables
}
