/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdministrativeRole;

import Business.Enterprise.Enterprise;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author dhava
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    public AdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.enterprise=enterprise;
        this.userProcessContainer=userProcessContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnManageEmployee = new javax.swing.JButton();
        btnManageusers = new javax.swing.JButton();
        btnManageOrganization = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Welcome Admin");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 210, 100));

        btnManageEmployee.setBackground(new java.awt.Color(0, 0, 0));
        btnManageEmployee.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnManageEmployee.setForeground(new java.awt.Color(255, 255, 255));
        btnManageEmployee.setText("Manage Employee");
        btnManageEmployee.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnManageEmployeeFocusGained(evt);
            }
        });
        btnManageEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnManageEmployeeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnManageEmployeeMouseExited(evt);
            }
        });
        btnManageEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEmployeeActionPerformed(evt);
            }
        });
        add(btnManageEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 290, 180));

        btnManageusers.setBackground(new java.awt.Color(0, 0, 0));
        btnManageusers.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnManageusers.setForeground(new java.awt.Color(255, 255, 255));
        btnManageusers.setText("Manage Users");
        btnManageusers.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnManageusersFocusGained(evt);
            }
        });
        btnManageusers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnManageusersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnManageusersMouseExited(evt);
            }
        });
        btnManageusers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageusersActionPerformed(evt);
            }
        });
        add(btnManageusers, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, 290, 180));

        btnManageOrganization.setBackground(new java.awt.Color(0, 0, 0));
        btnManageOrganization.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnManageOrganization.setForeground(new java.awt.Color(255, 255, 255));
        btnManageOrganization.setText("Manage Organization");
        btnManageOrganization.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnManageOrganizationFocusGained(evt);
            }
        });
        btnManageOrganization.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnManageOrganizationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnManageOrganizationMouseExited(evt);
            }
        });
        btnManageOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrganizationActionPerformed(evt);
            }
        });
        add(btnManageOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 290, 180));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageEmployeeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnManageEmployeeFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_btnManageEmployeeFocusGained

    private void btnManageEmployeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageEmployeeMouseEntered
        // TODO add your handling code here:
        btnManageEmployee.setBackground(Color.blue);
        // jButton2.setSize(20,20);
        btnManageEmployee.setForeground(Color.white);

    }//GEN-LAST:event_btnManageEmployeeMouseEntered

    private void btnManageEmployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageEmployeeMouseExited
        // TODO add your handling code here:
        btnManageEmployee.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_btnManageEmployeeMouseExited

    private void btnManageEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEmployeeActionPerformed
        // TODO add your handling code here:
        ManageEmployeeJPanel smn=new ManageEmployeeJPanel(userProcessContainer,enterprise.getOrganizationDirectory());
        CardLayout cl=(CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add("ManageEmployeeJPanel",smn);
        cl.next(userProcessContainer);

    }//GEN-LAST:event_btnManageEmployeeActionPerformed

    private void btnManageusersFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnManageusersFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageusersFocusGained

    private void btnManageusersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageusersMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageusersMouseEntered

    private void btnManageusersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageusersMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageusersMouseExited

    private void btnManageusersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageusersActionPerformed
        // TODO add your handling code here:
        ManageUserJPanel smn=new ManageUserJPanel(userProcessContainer,enterprise);
        CardLayout cl=(CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add("ManageUserJPanel",smn);
        cl.next(userProcessContainer);
        
    }//GEN-LAST:event_btnManageusersActionPerformed

    private void btnManageOrganizationFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnManageOrganizationFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageOrganizationFocusGained

    private void btnManageOrganizationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageOrganizationMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageOrganizationMouseEntered

    private void btnManageOrganizationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageOrganizationMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageOrganizationMouseExited

    private void btnManageOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrganizationActionPerformed
        // TODO add your handling code here:
        ManageOrganizationJPanel smn=new ManageOrganizationJPanel(userProcessContainer,enterprise.getOrganizationDirectory());
        CardLayout cl=(CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add("ManageOrganizationJPanel",smn);
        cl.next(userProcessContainer);
        
    }//GEN-LAST:event_btnManageOrganizationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageEmployee;
    private javax.swing.JButton btnManageOrganization;
    private javax.swing.JButton btnManageusers;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
